# Generated by Django 4.2.1 on 2023-05-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),

            ],
        ),
        migrations.CreateModel(
            name='habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
