# Generated by Django 4.2.1 on 2023-05-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segundoexamen', '0002_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(blank=True, max_length=70, unique=True),
        ),
    ]
