# Generated by Django 4.2.1 on 2023-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segundoexamen', '0003_clientes_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='fechafinal',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservas',
            name='fechainicio',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
