# Generated by Django 4.2.1 on 2023-05-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segundoexamen', '0004_reservas_fechafinal_reservas_fechainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitaciones',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='fechafinal',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='fechainicio',
        ),
    ]
